name: "Simple Test"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: "Simple Test Job"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Hello World"
        run: |
          echo "Hello from GitHub Actions!"
          echo "Runner: $(hostname)"
          echo "OS: $(uname -a)"